In [1]:
import pandas as pd

# Load datasets
load_df = pd.read_csv(r"C:\\Users\\reddy\\OneDrive\\Documents\\TSA-PROJECT\\data\\processed\\load_data_2022_final.csv")
weather_df = pd.read_csv(r"C:\\Users\\reddy\\OneDrive\\Documents\\TSA-PROJECT\\data\\raw\\weather_data.csv")

# Convert date columns
load_df['date'] = pd.to_datetime(load_df['date'])
weather_df['date'] = pd.to_datetime(weather_df['date'])

print(load_df.shape, weather_df.shape)
load_df.head()

(365, 2) (1461, 6)

        date      load
0 2022-01-01  178873.0
1 2022-01-02  179232.5
2 2022-01-03  179592.0
3 2022-01-04  178353.0
4 2022-01-05  177114.0

In [2]:
#merge on date
df = pd.merge(load_df, weather_df, on='date', how='inner')

print("Merged shape:", df.shape)
df.head()

Merged shape: (365, 7)

,date,load,temp_max,temp_min,precipitation,wind_speed,temp_avg
0,2022-01-01,178873.0,27.0,22.8,8.6,25.3,24.90
1,2022-01-02,179232.5,27.9,23.9,0.9,20.9,25.90
2,2022-01-03,179592.0,27.7,23.8,0.0,19.7,25.75
3,2022-01-04,178353.0,27.2,22.5,0.0,21.0,24.85
4,2022-01-05,177114.0,28.0,21.5,0.1,14.5,24.75

In [3]:
#check missing values
print(df.isnull().sum())

date             0
load             0
temp_max         0
temp_min         0
precipitation    0
wind_speed       0
temp_avg         0
dtype: int64

In [5]:
#save multivariate dataset
OUTPUT_FILE=r"C:\\Users\\reddy\\OneDrive\\Documents\\TSA-PROJECT\\data\\processed\\load_weather_2022.csv"

df.to_csv(OUTPUT_FILE,index=False)
print("Merged dataset saved at:",OUTPUT_FILE)

Merged dataset saved at: C:\\Users\\reddy\\OneDrive\\Documents\\TSA-PROJECT\\data\\processed\\load_weather_2022.csv

In [6]:
df[['load','temp_avg']].corr()

              load  temp_avg
load      1.000000  0.372499
temp_avg  0.372499  1.000000